# Site settings
title: Tom van Ommeren
email:
description: "International reinventor of wheels"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tomv.io" # the base hostname & protocol for your site
twitter_username: tomvanommeren
github_username:  tomv564
linkedin_username: tomvanommeren
google_analytics_tracking_id:  UA-7601332-2

# Build settings
markdown: kramdown

kramdown:
  input: GFM
