# Site settings
title: tomv.io
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tomv.io" # the base hostname & protocol for your site
twitter_username: tom.vanommeren
github_username:  tomv564
google_analytics_tracking_id:  UA-7601332-2

# Build settings
markdown: kramdown

kramdown:
  input: GFM
